"""Добавлены поля в Supply, SupplyItem и удалено purchase_price

Revision ID: 41ff306847a0
Revises: c997fbd84251
Create Date: 2025-05-08 21:01:26.533675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ff306847a0'
down_revision: Union[str, None] = 'c997fbd84251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('status', sa.String(), nullable=True))
    op.add_column('supply_items', sa.Column('received_quantity', sa.Integer(), nullable=True))
    op.add_column('supply_items', sa.Column('is_received', sa.Boolean(), nullable=True))
    op.drop_column('supply_items', 'purchase_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supply_items', sa.Column('purchase_price', sa.FLOAT(), nullable=True))
    op.drop_column('supply_items', 'is_received')
    op.drop_column('supply_items', 'received_quantity')
    op.drop_column('supplies', 'status')
    # ### end Alembic commands ###
