"""add price to supply_items

Revision ID: d3bae82c6eb5
Revises: 36274700c7a7
Create Date: 2025-05-14 08:53:12.538644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bae82c6eb5'
down_revision: Union[str, None] = '36274700c7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'supply_items',
        sa.Column('price', sa.Numeric(10, 2), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supply_items', 'price')
    # ### end Alembic commands ###
